### ISSUE TITLE
Releases aren't tagged

### ISSUE THREAD

**Issue by dnalot** [appiphony/appiphony-lightning-js#11]
For Bower etc. There are also too many files in `bower.json` (should be pretty much `dist`, `src`, and `*.txt`. Furthermore Bower's `name` (`appiphony-lightning-js`) differs from its install key (`aljs`). This is surprising but more importantly can't be its static resource name in Salesforce.

**Comment by kevinberonilla** [comment]
Good catch, thanks! We were toying around with install keys that would be simple to remember and decided on `aljs` but did not update the name of the component. We will be revisiting this in 0.1.3 (a smaller release coming very soon) for the sake of consistency. As far as what's included, we initially monitored which assets and directories SLDS included in their bower component and created ours to mirror what they offered. It appears this has changed, and excluding more of the files (like the `public` directory) would indeed be better for the user.

**Comment by dnalot** [comment]
Yeah using bower-installer to filter SLDS too. I think a lot of what they include is in case you intend to change the colors. But that's what the npm module is for. Trying it out today!
