### ISSUE TITLE
assetsLocation doesn't work for me

### ISSUE THREAD

**Issue by dnalot** [appiphony/appiphony-lightning-js#13]
My icons are in `/resource/slds/icons`. `assets/` is redundant so I don't have it. Shouldn't `assetsLocation` point to the `assets/` branch e.g. `/resource/slds/assets/?? Right now I can't load icons from your templates.

**Comment by kevinberonilla** [comment]
We are currently only supporting the file structure supplied by SLDS, as we have to solve for users who are using the system via its Unmanaged Package. It is the documented method for employing SLDS on an org (see https://developer.salesforce.com/trailhead/project/slds-lightning-components-workshop/slds-lc-1).

We will consider adding more settings in the future to support custom file structures, but the `assetsLocation` setting's behavior will need to remain the same in future releases.
