### ISSUE TITLE
DatePicker - Focusing input no longer opens datepicker

### ISSUE THREAD

**Issue by chewy2** [appiphony/appiphony-lightning-js#18]

**Comment by djlimbs** [comment]
Is this happening when the datepicker is empty, or when there is a date in the datepicker? The current UI in standard layouts in the New Lightning Experience only open on focus when the datepicker is empty, so if this is the behavior, it is as designed to follow what Salesforce is doing.

**Comment by kevinberonilla** [comment]
I saw it happening on empty as well. Something is preventing the Ember component from opening the datepicker on focus. Not sure what could be causing this.

**Comment by chewy2** [comment]
Okay figured out the issue. I never included to JS file.
