### ISSUE TITLE
Custom link to icons

### ISSUE THREAD

**Issue by matejp84** [appiphony/appiphony-lightning-js#22]
I'm constantly getting this error message in console and icons are not visible:
Unsafe attempt to load URL https://cs80.salesforce.com/assets/icons/standard-sprite/svg/symbols.svg#account from frame with URL https://c.cs80.visual.force.com/apex/VnosSerijskih#. Domains, protocols and ports must match.

Instead of using 
` <use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#search"></use>`
It should be:
`<use xlink:href="{!URLFOR($Resource.SLDS0120,'assets/icons/utility-sprite/svg/symbols.svg#search')}"></use>`
Only second link is working for me and icon is working that way.

This is probably SLDS issue just to let you know. I will also write there as well.

**Comment by kevinberonilla** [comment]
Hi, thanks for the input! We are keeping the icon paths to match those of SLDS's by default, however we have options to override them. Your suggestion for pointing to a static resource is correct if we're working with an org, but I assume SLDS is solving for uses outside of Salesforce so they set defaults to `/assets/...`.

One thing we've noticed is that Chrome will throw that error if you are working locally (trying to access an icon from a relative path on your drive). Our solution is to prototype our front-end with the `--allow-file-access-from-files` Chrome flag enabled. More information on this here: http://stackoverflow.com/questions/18586921/how-to-launch-html-using-chrome-at-allow-file-access-from-files-mode

*Do note that you should not be using that flag for normal browsing as it poses a security risk.* We use it purely for supporting local icons during prototyping.

**Comment by matejp84** [comment]
Hi,

I'm always working online on org and URL for must be always set to correct static resource. 
Is there any way to fix this issue? As currently I can only set URL for for my code, but it is pretty hard to fix it inside other js files. 
Main problem is with lookup control, when user selects one item, it gets a button on the right side to empty input field, but with this "bug" it is not visible and it is confusing to users.

**Comment by kevinberonilla** [comment]
Are you using the Ember component or the jQuery plugin for Lookups? In 0.1.3 and 0.1.2 (both of which were released recently), we have options to override the object icons for lookups.

In jQuery, if you set the `objectIconUrl` to blank, you can disable object icons altogether. Additionally, you can set your own custom URL with this option and a use a `var` representing your Static Resource's root in the string. For example: `var assetsLocation = '{!URLFOR($Resource.slds}';` is set on the Visualforce page and `objectIconUrl: assetsLocation + '/assets/icons/utility-sprite/svg/symbols.svg#search` is set on the Lookup plugin.

Is this what you're looking for?

**Comment by matejp84** [comment]
Yes you pointed me into right direction. After quick code inspect I found that I have to set it like this during init:

`...
assetsLocation: "{!URLFOR($Resource.SLDS0120,'')}",
objectIconUrl: "",
...`

Thanks for the help! :)
