### ISSUE TITLE
Datepicker onChange not firing

### ISSUE THREAD

**Issue by matejp84** [appiphony/appiphony-lightning-js#25]
Hi,

It seems that datepicker isn't firing onChange event when I select date from dropdown, but it is fired, if I manually write date in input.
Maybe I'm doing something wrong, but I have tried both:
set onChange on <input> and init onChange in javascript during datepicker initialization.

Or is there other way to catch that event and I'm missing something?

**Comment by kevinberonilla** [comment]
Would you be able to provide which version of ALJS you are using? Using 0.1.3 on a demo environment is calling the onChange correctly on both click and manual text edits.

Any code samples, such as your callback function, would help as well. Thanks!

**Comment by kevinberonilla** [comment]
Hi,

Do you have any updates for this? Any help with reproducing the issue would be great. Thanks!

**Comment by matejp84** [comment]
I have found a bug inside my code, this may be closed. Thank you.
