### ISSUE TITLE
How to get deselect event from lookup?

### ISSUE THREAD

**Issue by matejp84** [appiphony/appiphony-lightning-js#27]
As title says, how do we get deselect event from lookup? 
For example:
I select one item, but after that I press "X" and wish to search for new item.
This also concerns multi-data select lookup.

**Comment by matejp84** [comment]
Also how to get already selected items in multi-data select lookup? Do we have to manually build list in onChange function or is there already stored list of pills?

**Comment by djlimbs** [comment]
A hook to call the onChange callback on removal has been added for the 0.1.4 release.

For your second question, you should be able to call getSelection on the jQuery element with code like "$('#lookup-1').lookup('getSelection');" as documented here: http://aljs.appiphony.com/#!/lookups

**Comment by matejp84** [comment]
Oh thanks for the info, when can we expect 0.1.4 release?

**Comment by kevinberonilla** [comment]
We are working to get a release (which may be dubbed 0.2.0, depending on what changes we include) out by next week, if not sooner.

**Comment by matejp84** [comment]
One more question or maybe future request. 
Is it possible to reset lookup (empty selection) inside onChange event?
Currently calling setSelection with empty parameters locks page, because it goes into infinite loop. It would be nice to be able programmatically reset lookup even inside on change. 
I have currently situation in one project, where I have implemented searching for accounts with this lookup, but when user selects account I make new row in table below and lookup should be automatically empty and ready for next search.

**Comment by djlimbs** [comment]
Hi Matej,

The behavior you are describing is possible by setting the "clearOnSelect" attribute of the lookup to "true". This functionality is available in our 0.1.4 branch and will be available in master soon.

PS, please submit any requests in a new ticket, it is harder to track when commenting on closed issues. Thanks

**Comment by matejp84** [comment]
Hi, 

I'm still having issues with clear selection on lookups:
When clicking on X button on lookup I get exception:
ReferenceError: Can't find variable: selectResult
clearSingleSelectjquery.aljs-lookup.min.js:103:91
fnjquery-1.10.2.js:5644
dispatchjquery-1.10.2.js:5094
handlejquery-1.10.2.js:4765

using latest build 2.0 from git. OnChange isn't called, is there any workaround on this to get this call from this event so I know in my code when lookup has been cleared?

**Comment by matejp84** [comment]
Also noticed that calling $("#multiLookup").lookup('setSelection',[]); doesn't clear lookup, but leaves one element still selected.

**Comment by kevinberonilla** [comment]
Good catch! This will be a part of our next release. Thanks!
