### ISSUE TITLE
Modal dialog background using wrong CSS classes

### ISSUE THREAD

**Issue by matejp84** [appiphony/appiphony-lightning-js#30]
Hi,

I have just found that the latest version of this library is using wrong classes for dialog background (blueish one with transition). 
Instead of using: slds-modal-backdrop slds-modal-backdrop--open 
it uses: slds-backdrop slds-backdrop--open

**Comment by kevinberonilla** [comment]
Hello,

Please update your SLDS static resource to 0.12.0 or newer. SLDS's 0.12.0 release introduced new markup for modals, which require the slds-backdrop block tree, which now looks just like the original modal backdrop. Please see https://www.lightningdesignsystem.com/components/modals/ for more information on this.

According to 0.12.0's release notes, the slds-modal-backdrop block tree is now deprecated and should no longer be used. https://www.lightningdesignsystem.com/release-notes/

**Comment by matejp84** [comment]
Looks like I was using some beta version of 12 version with old class names. It is working now perfectly Thank you for your help.
