### ISSUE TITLE
Calling $('#someid').picklist('getValue'); throws exception

### ISSUE THREAD

**Issue by matejp84** [appiphony/appiphony-lightning-js#31]
As title says, here is exception message:
TypeError: l[o] is not a function. (In 'l[o](i[1],i[2])', 'l[o]' is undefined)
column: 2815
line: 1
message: "l[o] is not a function. (In 'l[o](i[1],i[2])', 'l[o]' is undefined)"

picklist is initialized with: $('#serviceStatusPicklist').picklist();
html is almost identical as in documentation except first row: 
<div class="slds-picklist" aria-expanded="true" data-aljs="picklist" id="serviceStatusPicklist">

**Comment by djlimbs** [comment]
Thanks for finding this, it looks like that function may have gotten overwritten by getValueId in the latest branch. We will add this function back in for the next release. In the meantime, using getValueId may serve your purposes.

**Comment by matejp84** [comment]
With new release getValue works as it should, but I'm not getting onChange event triggered.
Using this code:
`$("#userList").picklist({
                        onChange: function(obj) {
                            console.log(obj);
                        }
                    });`
Console log never executes. Can you please check if this works?

**Comment by djlimbs** [comment]
How are you updating the picklist value? With user interaction or with the setValue method?

**Comment by matejp84** [comment]
With user interaction.

**Comment by djlimbs** [comment]
Please provide more info (code sample, browser) as we are unable to replicate this bug on our side. Thanks

**Comment by kevinberonilla** [comment]
Hi @matejp84! Could this be the same problem occurring in #40?
