### ISSUE TITLE
Issue with Tab focus ..

### ISSUE THREAD

**Issue by ajith007** [appiphony/appiphony-lightning-js#32]
The Tab focus is gone when I click outside of the tabs. The blue underline will disappear if I click inside the tab content. I'm trying pretty much the same source as in, http://aljs.appiphony.com/demo-tabs.html 

Attached zip has my HTML and the doc has the screenshot. 

[tabstest2.zip](https://github.com/appiphony/appiphony-lightning-js/files/118320/tabstest2.zip)
[aljs_tabs_screenshot.docx](https://github.com/appiphony/appiphony-lightning-js/files/118314/aljs_tabs_screenshot.docx)

Any idea what could be wrong?

**Comment by kevinberonilla** [comment]
Hi Ajith,

This is actually a bug that's a part of SLDS at the moment. Please see this SLDS issue for more information: https://github.com/salesforce-ux/design-system/issues/106

Manually editing the stylesheet from 0.12.x with the solution kaelig posted seems to be the accepted solution until the next version of SLDS is released.

**Comment by ajith007** [comment]
Thanks so much Kevin, that helped! 

Instead of editing the SLDS CSS, I put the fix inside the <style> element in the page itself as below.

<style type="text/css">
        html, body {
            margin: 0;
            padding: 2px;
            width: 100%;
            height: 100%;
            box-sizing: border-box;
        }

        .slds .slds-active .slds-tabs--default__link {
            border-color: #0070d2;
            color: #16325c; 
        }
    
        .slds .slds-active .slds-tabs--default__link:focus {
            color: #0070d2; 
        }
    </style>

**Comment by kevinberonilla** [comment]
Hi Ajith,

Just letting you know that SLDS 0.12.2 which was released a few days ago fixes this issue.

**Comment by ajith007** [comment]
Hi Kevin, Thank you for letting me know. I'll get the latest version. :)
