### ISSUE TITLE
Modals - Issue with icon in modal header (IE11)

### ISSUE THREAD

**Issue by kolmicenko** [appiphony/appiphony-lightning-js#33]
Hi, there is an issue with close icon in modal header (IE11).

SLDS version : 0.12.1
svg4everybody version: 2.0.3
ALJS version: 0.1.3

The icon is shown in Chrome correctly. As I tried modals component on your website (IE11), the icon is there hidden too.

My source code:
`<div class="slds-modal__header">
                    <h2 class="slds-text-heading--medium">New opportunity</h2>
                    <button class="slds-button slds-modal__close" data-aljs-dismiss="modal">
                        <svg aria-hidden="false" class="slds-button__icon">
                            <use xlink:href="{!URLFOR($Resource.SLDS, '/assets/icons/action-sprite/svg/symbols.svg#close')}"></use>
                        </svg>
                        <span class="slds-assistive-text">Close</span>
                    </button>
                </div>`

Many thanks

**Comment by kevinberonilla** [comment]
Hello,

This is a known issue for IE11 where the browser cannot properly display SVGs in this manner. There is a fix for this though: a shim known as SVG for Everybody (https://github.com/jonathantneal/svg4everybody)

You will need to save this as a static resource on your org and run the function highlighted in their git repo. There are also talks of including this script automatically on the Salesforce side so you won't have to manage your own static resource. Right now this is only a consideration though. See https://github.com/salesforce-ux/design-system/issues/140 for more information.

**Comment by kevinberonilla** [comment]
Hello,

Were you able to get this solution working for you?

**Comment by kolmicenko** [comment]
Hello,
yes. The problem is solved. Last updates of SLDS and ALJS solved the problem.

Thank you
