### ISSUE TITLE
Lookup - selectResult not defined 

### ISSUE THREAD

**Issue by smukov** [appiphony/appiphony-lightning-js#36]
In `jquery.aljs-lookup.min.js` there's a mistake in function `clearSingleSelect`.

Instead of: `e.settings.onChange(selectResult, !1)`, it should probably be `e.settings.onChange(e.selectResult, !1)`

**Comment by kevinberonilla** [comment]
Hello smukov! Thanks for pointing this out. This is actually a bug we found and fixed while enhancing the lookup plugin for another user's issue, but the solution has not been officially released yet. If you want to get the latest development version of the plugin, you can download the develop branch here: https://github.com/appiphony/appiphony-lightning-js/tree/develop

**Comment by smukov** [comment]
I fixed this manually for now, but I'll probably download your develop version on Monday. Thanks for that suggestion, and thank you for your awesome work!

**Comment by djlimbs** [comment]
no, you're awesome!
