### ISSUE TITLE
Multiple tab levels not working

### ISSUE THREAD

**Issue by matejp84** [appiphony/appiphony-lightning-js#37]
Creating more than one level of tabs isn't working. 
Example:
Have 3 tabs and then inside first tab another 3 nested tabs. When clicking on inner tab, inner tabs disappears and only content of tab is visible. Also outer tabs are deselected so user cannot know in which tab he/she is. 
If I'm mistaken and this is working as intended, I would like to ask for simple example of code for nested tabs.

**Comment by kevinberonilla** [comment]
We have not tested for nested tab setups, but I do believe it is possible to support your case in the next release. We will work on a solution for you and keep you updated here. Thanks!

**Comment by kevinberonilla** [comment]
Hello, we have committed a solution to your problem in our `develop` branch. Can you please try the branch's tab plugin (https://github.com/appiphony/appiphony-lightning-js/blob/develop/dist/jquery/jquery.aljs-tabs.min.js) to test if this fixes your issue?

**Comment by matejp84** [comment]
It works! Thank you very much :)

**Comment by kevinberonilla** [comment]
You're welcome! We're glad to you caught this, thank you.
