### ISSUE TITLE
Muliselect drag and drop not working on Firefox browser

### ISSUE THREAD

**Issue by kanwalpreet-singh** [appiphony/appiphony-lightning-js#42]
Muliselect drag and drop not working on Firefox browser even for the demo website.

**Comment by kevinberonilla** [comment]
Thank you for logging this! We will address this issue as soon as possible.

**Comment by kevinberonilla** [comment]
Hello @kanwalpreet-singh! It appears this is actually a browser compatibility issue with the HTML5 `draggable` attribute. Firefox does not support this attribute without the JS hack documented here: http://stackoverflow.com/questions/3977596/how-to-make-divs-in-html5-draggable-for-firefox

Try adding the script from the top answer to see if this fixes your issue. We have decided not to include this on the plugin itself as we want to avoid collisions with other scripts developers may already have for their application.
