### ISSUE TITLE
Incorrect initialization demo on http://aljs.appiphony.com/#!/multiSelects

### ISSUE THREAD

**Issue by AnzeKovac** [appiphony/appiphony-lightning-js#44]
In the demo initialization example MultiPicklist function was used instead of MultiSelect.
![image](https://cloud.githubusercontent.com/assets/7703090/17508413/1ebf428e-5e15-11e6-8c64-aed57ce198c9.png)

Same mistake repeats in the Methods section of the same page.

Also after changing method name to 
$('[data-aljs="multi-select"]').multiSelect('getSelectedItems')); I get "Uncaught ReferenceError: option is not defined" on aljs-all.min.js

**Comment by kevinberonilla** [comment]
Thanks for logging this! We didn't catch this the first time when we renamed some of the plugins. We'll get this fixed ASAP.
