### ISSUE TITLE
Problem with Close Image on Lookup

### ISSUE THREAD

**Issue by mdoggett1976** [appiphony/appiphony-lightning-js#48]
Hi

I have implemented a Lookup for objects in VisualForce within Salesforce. However, when I select an item, the x that should appear at the right of the field to clear the selected item does not display.

I assume this is because a pill is created when an item is selected and internally references the x image. However, I am using a static resource contains all images and hence the image is not being found so does not display.

Is there anyway to override the image displayed in the pillbox so I can redirect it to get it from the Static Resource

Thanks

**Comment by kevinberonilla** [comment]
Hello @mdoggett1976, do you also have all of the SVG sprite sheets provided by SLDS in your static resource? If so, it's all a matter of overriding ALJS's global settings to suit your needs. You can do this by inserting the following code before you initialize any of ALJS's plugins:

```
$.aljsInit({
    assetsLocation: {{Path to the SLDS's assets folder}},
    scoped: false // Change to true if you are scoping SLDS elements
});
```

Do note that the path needs to specify the directory containing the `assets` folder itself, and that the folder structure provided by SLDS needs to remain in tact in order for our plugins to find the resources they need. Please let me know if this information helps.

**Comment by mdoggett1976** [comment]
Hi

Yep that worked perfectly thanks
