### ISSUE TITLE
Upgrade v2.1.2 SLDS

### ISSUE THREAD

**Issue by tuxolino** [appiphony/appiphony-lightning-js#49]
Hi guys,

A few minutes ago, version SLDS v2.1.2 was released. 
Do you have in mind if/when an updated version of ALJS will be released to support new SLDS version ?

Best Regards,

**Comment by kevinberonilla** [comment]
Hello! Yes, we do plan on supporting the 2.1.2 SLDS release that just came out, however we have not yet planned a date for the ALJS release. We must first comb through their changelog to see what patterns have changed and test out each of our plugins for new bugs that may have come up.

Have you noticed anything in particular in the new release that is affecting your code? Any help identifying these issues are appreciated, and we may even be able to provide you with some temporary fixes on our `development` branch.

**Comment by vscuorzo** [comment]
@kevinberonilla I'm running into an issue currently with the notification plugin (toast type) when paired with LDS 2.0.3. It looks like  LDS wraps the notification with a container element with the "slds-notify_container" class which should probably be the element that gets the "slds-hide" class. More importantly though, the notification does not get hidden after initialization and any attempts to hide notifications using method calls result in the following error: "Uncaught ReferenceError: $notification is not defined". Looking at the source, I think there are some references to "$notification" that should be to "$node". I think it would be fairly easy to update this plugin to work properly.

**Comment by kevinberonilla** [comment]
@vscuorzo good catch! We're still in the middle of reviewing how the changes to the Winter release (2.1.x) affect our code and your contribution is greatly appreciated.

Once we update this issue on our side we will let you know so you can update your ALJS to the version in the `development` branch, which is where we're building our `2.0.1` release.

**Comment by vscuorzo** [comment]
@kevinberonilla I've submitted a pull request with a fix for the error I mentioned so you can just merge that in. I didn't do anything to address the container element change in LDS because once the Javascript issue was fixed the plugin does function as expected and any negative impact seems minimal.

**Comment by kevinberonilla** [comment]
The pull request has been merged in `development` and will make it to the next release. Thanks!
