### ISSUE TITLE
Lookup inside a Modal - How to resize Modal?

### ISSUE THREAD

**Issue by cv-alexanderyhap** [appiphony/appiphony-lightning-js#51]
How can I get the modal's height to resize when the lookup box appears?

<img width="687" alt="screen shot 2016-09-26 at 3 44 43 pm" src="https://cloud.githubusercontent.com/assets/20650028/18849270/35b2adf8-8400-11e6-91ce-82a0a4612ce8.png">

**Comment by kevinberonilla** [comment]
Hello @cv-alexanderyhap! Our team has also experienced this issue on a number of our projects. Our solution was done through CSS: add an `overflow: visible` style via a class on the `slds-modal__content` element. Do note that this will show overflow content for anything in the modal's body, which could be problematic if you have other content aside from this lookup.
