### ISSUE TITLE
Support "slds-scope" scoping class

### ISSUE THREAD

**Issue by dsharrison** [appiphony/appiphony-lightning-js#79]
The newly introduced `<apex:slds />` tag adds a Salesforce managed instance of the lightning design system into Visualforce pages. Unfortunately, this uses the scoping class "slds-scope" instead of "slds". This request is to allow the ALJS scoping class to be set during init (possibly accept a string instead of a boolean).

**Comment by kevinberonilla** [comment]
Hi @dsharrison, this change is actually going to be merged for our upcoming release (an official time for this release is TBD). There are a number of tested bug fixes and general support for SLDS 2.2.2 currently available in the `development` branch (https://github.com/appiphony/appiphony-lightning-js/tree/development) if you need support for this immediately.

The new way to use the init is as follows:
```
$.aljsInit({ // Below are the new defaults
        assetsLocation: assetsLocation,
        scoped: true,
        scopingClass: 'slds-scope'
    });
```
 Let us know if this helps!

**Comment by dsharrison** [comment]
@kevinberonilla This looks like it will work perfectly! We have manually modified the scoping class being applied right now but during our next development cycle we will see if this has been released and if so switch over.

**Comment by dsharrison** [comment]
I just wanted to follow up that the ability to set a scoping class is great, but the simple change to using the `slds-scope` class by default was even better. I am going to close this issue since this is resolved for us.
